# nm-connection-editor, blueman, nwg-displays, pwvucontrol
windowrule = float on, match:class (nm-connection-editor|blueman-manager|nwg-displays|com.saivert.pwvucontrol)
windowrule = center on, match:class (nm-connection-editor|blueman-manager|nwg-displays|com.saivert.pwvucontrol)
windowrule = size 800 800, match:class (nm-connection-editor|blueman-manager|nwg-displays|com.saivert.pwvucontrol)

# Helvum
windowrule = float on, match:title ^(.*Helvum.*)$
windowrule = center on, match:title ^(.*Helvum.*)$
windowrule = size 1000 1000, match:title ^(.*Helvum.*)$

# cpupower-gui
windowrule = float on, match:class cpupower-gui
windowrule = center on, match:class cpupower-gui
windowrule = size 900 900, match:class cpupower-gui

# ZenBrowser Picture-in-Picture
windowrule {
  name = zen
  match:class = zen
  match:title = ^Picture-in-Picture$
  float = on
  pin = on
  size = 480 270
  move = (monitor_w*0.74) (monitor_h*0.74)
}

# Media Viewers
windowrule = float on, match:title ^(Media viewer|图片查看器)$
windowrule = float on, match:class ristretto
windowrule = center on, match:title ^(Media viewer|图片查看器)$
windowrule = size 1600 900, match:title ^(Media viewer|图片查看器)$

# Common App Windows
windowrule {
  name = common
  match:title = ^(.*(打开文件|工作区|另存为|Open Folder|Open File|Select a File|Save As|File Upload).*)$
  float = on
  center = on
  size = 900 1000
}

